maplibre/maputnik

src/about.jsx
src/app.jsx
src/toolbar.jsx
src/workspace.jsx

This adds a simple about page with basic infos (taken verbatim from the readme, feel free to adjust/modify) and a link to this github repository.

add about page

---

src/components/App.jsx

This should clear commit history of styles. If style is not formatted, diff may look like this:
https://github.com/openmaptiles/osm-bright-gl-style/commit/c514b0ce7fa5335f3b0e8334aed0ea0d05f8d5cc

Format style on download

---

src/components/App.jsx
src/components/Toolbar.jsx
src/components/map/MapboxGlMap.jsx
src/components/modals/ExportModal.jsx
src/components/modals/SettingsModal.jsx
src/config/tokens.json
src/libs/style.js

This resolves #80 and #79.
@jirik I don't think you need to do more to integrate this into GIST saving (except perhaps also call the `stripMetadata` function). Because the access key is stored via the settings.

Default access token

---

src/components/Toolbar.jsx
src/components/inputs/CheckboxInput.jsx
src/components/inputs/StringInput.jsx
src/components/modals/ExportModal.jsx
src/styles/_base.scss
src/styles/_export.scss
src/styles/_modal.scss
src/styles/index.scss

When saving to Gist, user can choose if he wants a preview. If so, he needs to add access token that can be generated for free from the link below the input. It is the same access token from style settings.
In this PR, I changed also behaviour of two general components:
fab004cdfe4de1446074fd60e50b1d775a8d26d7 I did this because it did not call onChange listener if new value was empty string.
3b7fb7ae75c88f22bd0489a00d6fd5261618ebee I did this because it CheckBox always showed "check" icon despite being true or false.
@lukasmartinelli please check two mentioned commits carefully.

Gist preview & access token

---

src/components/fields/ColorField.jsx

I've fixed the alpha value slider in the color picker, the issue was the color module returned `alpha` rather than `a` which `react-color` was expecting.
This fixes issue #44

Alpha value slider fix (#44)

---

package.json

This should hopefully make PRs #133 and #134 pass again. Note that https://github.com/nkbt/react-collapse/commit/24631961919e26d852120262b0cc2180e9c33ea8 seems to be the commit that caused our builds to fail.

Update react-height peer dependency version

---

package.json

This should fix the ongoing CI failures when running npm 4.
As far as I can tell, this version update does not cause any issues building or running the editor.

Update react-collapse to ^4.0.2

---

.babelrc
package.json

When using maputnik as a dependency in another project (e.g. to use the LayerEditor component), webpack doesn't read the babel config. Webpack does read it if we put it in a ```.babelrc``` file instead

Move babel config out of package.json

---

src/components/fields/ColorField.jsx

This gets rid of a warning for ColorField:
```
warning.js:36 Warning: Unsupported style property background-color. Did you mean backgroundColor? Check the render method of `ColorField`.
```

Prevent warning for ColorField

---

src/styles/_input.scss

Use "position: absolute" so that autocomplete follows the field when you scroll.
Match autocomplete width with element width (accounting for padding)
Previously, the autocomplete dialog would appear below the field (e.g. font) and not move if you scrolled the symbol-layer edit window to a different position. This change makes it so the autocomplete dialog follows the field when you scroll. There are also some changes to width to ensure it matches the width of the input field.

Improve autocomplete styling

---

src/components/fields/SpecField.jsx
src/components/inputs/DynamicArrayInput.jsx
src/styles/_input.scss

Variable length array fields (such as `line-dasharray`) are currently fixed-length in the editor.
In the case of `line-dasharray`, it has no default defined in the v8 spec, so its default value is an empty array, making it entirely uneditable.
This adds a DynamicArrayInput for use with all array fields that do not have a fixed length. Adding and removing fields works similar to ZoomSpecField.
Fixed-length array fields still use ArrayInput.

Add DynamicArrayInput for handling variable-length array fields

---

src/components/modals/OpenModal.jsx

This suggests closing the "open" dialog after the user chooses a new style (by uploading or from the gallery).

Close the "open" dialog after choosing a new style

---

src/components/inputs/DynamicArrayInput.jsx

When you edit a dash array field you get a react warning about missing key, this PR fixes that warning

Put key on the right element

---

.babelrc

This is a follow-up to #144 on the current code base I get (this PR fixes that):
```
ERROR in ./~/maputnik/src/components/layers/LayerEditor.jsx
Module build failed: SyntaxError: Unexpected token (45:19)
43 | /** Layer editor supporting multiple types of layers. */
44 | export default class LayerEditor extends React.Component {
> 45 |   static propTypes = {
|                    ^
46 |     layer: React.PropTypes.object.isRequired,
47 |     sources: React.PropTypes.object,
48 |     vectorLayers: React.PropTypes.object,
```

Add transform-class-properties plugin to babel config

---

src/components/fields/SpecField.jsx
src/components/fields/ZoomSpecField.jsx

This gets rid of the propTypes warnings which you can encounter when using ```fill-antialias``` or ```fill-translate``` in a MapBox GL Style JSON document
@tbarsballe pointed out that because these props accept functions, so the current behaviour actually makes sense
closes #147

Make sure propTypes accept what gets passed in

---

src/components/filter/SingleFilterEditor.jsx

This pull request auto converts `"true"` -> `true` in filters. The downside of this is that you can no longer test against the string `"true"`. This seems a minor issue and is inline with the current handling of numbers where `"3"` -> `3`.
Fixes #114

Added true/false conversion to filter field

---

package.json
src/components/Toolbar.jsx
src/styles/_toolbar.scss
test/specs/simple.js

Fixes logo styling in the toolbar, the logo is no longer stretched. Also switched to the logo in [maputnik/design](https://github.com/maputnik/design).
Before
After

Fixes logo styling in toolbar

---

package.json
src/components/layers/CommentBlock.jsx

Added the missing doc tooltip on the comments field (which also fixes the styling issues). Also updated 'react-collapse' so the tooltip is now visible and not hidden by the `overflow: hidden` from the old version of react-collapse

Added comments field doc and updated react-collapse to fix styling

---

src/config/styles.json
src/config/tilesets.json

Changes the HTTP paths for loading thumbnail images and one tile layer to HTTPS to avoid Mixed Content errors. Also closes #153, but it looks like there's a separate issue with the Tilezen style where it returns HTTP 401 unauthorized errors for the Mapbox fonts, so I'm guessing the API key for that style may be invalid here https://rawgit.com/lukasmartinelli/tilezen-gl-style/master/style.json

Fix insecure asset loading

---

package.json
src/components/modals/ExportModal.jsx
src/styles/_export.scss

Closes #171, and adds to functionality mentioned in #120. Adds a copy to clipboard button and an input with the URL including a pre-populated style parameter after a user exports a style to a gist

Add share style link, copy button

---

src/components/fields/FunctionSpecField.jsx

Fixes some lingering issues from #161. I noticed that when I load a style where the type wasn't explicitly identified on a data driven style that it would default to `categorical`. Instead of this, if an uploaded style doesn't have a `type` property this checks the `fieldSpec` to determine what it should be.
According to the [style spec details on functions](https://www.mapbox.com/mapbox-gl-js/style-spec/#types-function), any property that supports `interpolated` must be numeric and defaults to `exponential`, and any property that is numeric and supports functions (checked elsewhere) must support `interval`. I'm using that logic in `getFieldFunctionType` to determine which to assign, and it's worked on styles I've tested for `exponential`, `interval`, and `categorical`

Assigning default function type from spec

---

src/components/Toolbar.jsx
src/styles/_scrollbar.scss
src/styles/_toolbar.scss

When the editor has a small width, the toolbar actions were wrapping covering other parts of the UI. This fix add overflow scroll to the toolbar actions. 
You can see the issue <http://orangemug.github.io/responsurl/?w=624&h=768&url=https://maputnik.github.io/editor> where "Layers" and "Help" overflow.
This is mainly an issue during debugging at the moment (inspector open). However I will shortly be adding an additional action also.

Added css overflow scroll to toolbar actions

---

README.md
config/webpack.config.js
package.json

I've disabled `webpack-dev-server` polling by default. Most users won't need this enabled and for those that don't require polling it was causing lots of CPU usage. Which was causing my cafe trips to work on maputnik to be cut short due to a drained battery  ☹️
This should be a better default for most users. I've also verified works inside a docker container just fine.

Disable polling by default

---

config/webpack.production.config.js
package-lock.json
package.json

Added [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) so we can start tracking the maputnik/editor build size across time. Note once CircleCI is enabled (see #173) this will be written to the build directory and saved as an artifact.
Here an example of what our current build looks like https://75-84182601-gh.circle-artifacts.com/0/tmp/circle-artifacts.KpP7hcS/build/bundle-stats.html

Webpack bundle analyzer

---

src/components/fields/ColorField.jsx

If the color is invalid in the style it can cause the editor to stop rendering. This fixes that.
To reproduce try changing a color to something like `rgb(,0,0)` which will cause an error. If you now reload the editor it'll be stuck in a broken state.

Catch invalid color

---

package.json
src/components/App.jsx
src/components/layers/LayerList.jsx
src/components/map/FeatureLayerPopup.jsx
src/components/map/MapboxGlMap.jsx
src/styles/_popup.scss

The not obvious piece of code is responsible for ensuring that when you click on a layer that is a part of a collapsed layer group, the layer group will expand on click as well.

Clickable layer tooltips (#60)

---

config/webpack.loaders.js
package.json
src/components/App.jsx

This is a hack, but seems like it's generally pretty useful to be able to parse `mapbox://` urls. See comment in `config/webpack.loaders.js`
Fixes #224

Added support for mapbox:// urls to fetchSources

---

package-lock.json
package.json
src/components/icons/LayerIcon.jsx
src/components/layers/LayerEditor.jsx
src/components/layers/LayerTypeBlock.jsx
src/components/map/MapboxGlMap.jsx
src/components/modals/AddModal.jsx
src/components/modals/SourcesModal.jsx
src/components/sources/SourceTypeEditor.jsx
src/config/layout.json

Related to #262. Almost there, it seems like if you load a style with hill shading you can add further hill shading layers. However if you add a hill shade layer to an empty style the mgl validator throws an error. 
See <https://224-84182601-gh.circle-artifacts.com/0/tmp/circle-artifacts.kxhzGDE/build/index.html>

Added hillshading support

---

package-lock.json
package.json

Updated from personal fork/branch `orangemug/mapbox-gl-inspect#fix/only-vector-sources`

Updated mapbox-gl-inspect to v1.3.0

---

src/components/inputs/AutocompleteInput.jsx

Fix regression introduced by https://github.com/maputnik/editor/pull/226
The autocomplete list was not displayed correctly.
Tested on ubuntu/chrome and mac/safari

Use a fixed position for autocomplete menu

---

src/components/fields/_DataProperty.jsx
src/styles/_zoomproperty.scss

Fixes #276. I haven't extensively tested this yet, but I wanted to see if this approach makes sense in general, and I can take a closer look if it does.
Modifies the data property field to only creates the zoom input if the provided value is an object, otherwise ignores it and allows the data value line to take the full width. Also modifies `changeStop` to return just the `value` property if `zoom` is undefined.
This should handle any styles imported with the array syntax and without zooms, but still defaults to creating stops with zoom values attached when the data function button is selected.

Handle data functions without zoom

---

src/components/modals/ExportModal.jsx
src/styles/_base.scss

Anonymous gists are no longer supported by GitHub. See <https://github.com/maputnik/editor/issues/269>
Disabling until we get GitHub auth working.

Disable gist export

---

src/components/Toolbar.jsx
src/components/layers/LayerList.jsx
src/styles/_components.scss
src/styles/_input.scss
src/styles/_toolbar.scss

Changed from links `<a/>` without `href` to proper buttons so they are keyboard accessible

Made buttons keyboard accessible

---

package.json
src/components/layers/Collapse.jsx
src/components/layers/CollapseReducedMotion.jsx
src/components/layers/LayerEditorGroup.jsx
src/libs/accessibility.js
src/styles/_input.scss
src/styles/_layer.scss

See <https://css-tricks.com/introduction-reduced-motion-media-query/>. `prefers-reduced-motion` currently only supported in safari.

Added prefers-reduced-motion support

---

package-lock.json
package.json
src/components/App.jsx
src/components/fields/_ZoomProperty.jsx
src/components/filter/FilterEditor.jsx
src/components/inputs/NumberInput.jsx
src/components/inputs/StringInput.jsx
src/components/layers/JSONEditor.jsx
src/components/layers/LayerEditor.jsx
src/components/layers/LayerIdBlock.jsx
src/components/layers/LayerSourceBlock.jsx
src/components/layers/LayerSourceLayerBlock.jsx
src/components/layers/LayerTypeBlock.jsx
src/components/layers/MaxZoomBlock.jsx
src/components/layers/MinZoomBlock.jsx
src/components/map/MapboxGlMap.jsx
src/components/map/OpenLayers3Map.jsx
src/components/modals/AddModal.jsx
src/components/modals/ExportModal.jsx
src/components/modals/SettingsModal.jsx
src/components/modals/SourcesModal.jsx
src/components/sources/SourceTypeEditor.jsx
src/libs/diffmessage.js
src/libs/filterops.js
src/libs/layer.js

This enable adding of terrarium tiles. Also updated `@mapbox/mapbox-gl-style-spec` to `v12.0.0`

Added support for encoding to raster-dem source

---

package-lock.json
src/components/fields/ColorField.jsx
src/components/inputs/AutocompleteInput.jsx
src/components/inputs/NumberInput.jsx
src/components/inputs/StringInput.jsx

`<input>`'s don't need spell checking, so disabling.

Disable spellcheck on <input/>'s

---

src/components/App.jsx
src/template.html

An initial attempt at adding 'color blindness emulation' to the editor. To use it add a query string param `color-blindness-emulation` with one of the following values. Note the links point to the branch build of the editor for testing.
- [protanopia](https://482-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html?style=https://osm-liberty.lukasmartinelli.ch/style.json&color-blindness-emulation=protanopia)
- [protanomaly](https://482-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html?style=https://osm-liberty.lukasmartinelli.ch/style.json&color-blindness-emulation=protanomaly)
- [deuteranopia](https://482-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html?style=https://osm-liberty.lukasmartinelli.ch/style.json&color-blindness-emulation=deuteranopia)
- …

Color blindness emulation

---

src/components/Toolbar.jsx
src/components/inputs/SelectInput.jsx
src/components/layers/LayerTypeBlock.jsx
src/styles/_react-collapse.scss
src/styles/_toolbar.scss

- Logo DOM sctrucutre now valid, no longer `<a/>` within `</a>`
- `data-wd-key` not longer required
- `maputnik-doc-popup` not longer hidden by LayerEditor accordion

Small bug fixes

---

src/components/App.jsx

`normalizeSourceURL` was `undefined` when imported using 
```
import mapboxUtil from 'mapbox-gl/src/util/mapbox'
```
This appears to fix that issue.

Fixed normalizeSourceURL import issue

---

src/styles/_layout.scss
src/styles/_react-collapse.scss

The contents of the JSON editor could cause <LayerEditor/> to overflow.

Fixed <LayerEditor/> overflow issues

---

src/styles/_base.scss

The UI is 100% height so prevent bounce scroll on OSX

Prevent bounce scroll on <body/>

---

src/styles/_components.scss

Map container overflows causing odd zoom behaviour (fixes #260)

Fixed map width so it no longer overflows

---

test/functional/index.js

The survey popup was causing the tests to fail.
Also I forgot that node v8 build is the only runner that runs the UI tests, so that build wasn't just being flakey.... ooops!

Disable survey in test runner

---

src/libs/style.js

At the moment when starting the app we don't see a default map which should be the item at the position 0 in `src/config/styles.json`.
https://rawgit.com/openmaptiles/klokantech-basic-gl-style/master/style.json
is the default style.
This PR fixes the issue.
Is this regexp `mapStyle.glyphs.match(/\.tileserver\.org/)` an outdated one?
Does it make sense to simplify the code this way or are there use cases I am not aware of?
I see in the code that sometimes you're using `;` and sometimes not, what is preferred?

Fix glyph access key for openmaptiles

---

src/libs/style.js

Partial revert of #367 because it was replacing `{key}` glyphs regardless of what source they were from

Updated regex to tilehosting.com

---

src/config/tilesets.json

To prevent confusion - `free` is working (redirected to `maps`), but `maps` is what Maptiler Cloud shows as URL in the dataset settings.

Update tilehosting URL

---

src/config/styles.json

GitHub Pages is available for OSM Liberty, so we could use it instead of jsdelivr.net for the style URL (no need to update the URL if the style changes).
Also updated the thumbnail URL.

Use GitHub Pages for OSM Liberty

---

src/mapboxgl.css

The mapbox-gl popup tip was appearing white in the states, `top-left`, `top-right`,  `bottom-left`, `bottom-right`.

Fixes for 'mapboxgl-popup-tip' border color.

---

.circleci/config.yml
README.md
appveyor.yml

- Closes #445. 
- Removes the part regarding the Maputnik CLI. We could add it again if it would be available again in the future (maputnik/editor#360).

Remove node v9 from appveyor and update readme

---

src/components/App.jsx

- Allow shortcuts to trigger from the shortcut modal
- Fix inspect/map toggle shortcut

Shortcut fixes

---

test/functional/modals/index.js

- Add test for Thunderforest access token. 
- Style renderer: It was skipped and now, after https://github.com/maputnik/editor/pull/397, could be used again.

Update tests for style settings modal

---

src/styles/_layer.scss

Before
After
Demo: <https://1175-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.35/0/0>

Increase more-menu icon size, broken by react-icons update

---

src/components/layers/LayerList.jsx
src/styles/_layer.scss

When dragging a layer, there are the following issues:
- The dragged layer changes its font (not Roboto anymore).
- Sometimes the dragged layer is rendered behind other layers/groups.
This PR fixes these issues ([background information](https://github.com/clauderic/react-sortable-hoc#item-disappearing-when-sorting--css-issues)).
Also removes the border (= the underline) while dragging, it is hard to spot anyway and sometimes looks weird.
Demo: https://829-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html

Style layer which is dragged

---

Dockerfile

assets of frontend is built by the last `RUN`,
so we just need to host the built assets.
in node, python is required, so use python simple server to do this.

make docker simpler

---

src/libs/mapbox-rtl.js

Fixes the Chrome deprecation notice:
Demo: https://964-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html

Set MIME type for RTL blob

---

src/components/fields/SpecField.jsx

Fixes #481 - this is just a hotfix, a more complete fix would need to add support for dynamically adding/editing format parts, as in [this example style](https://github.com/mapbox/mapbox-gl-js/blob/master/test/integration/render-tests/text-field/formatted-line/style.json)

Use StringInput for 'formatted' field type

---

Dockerfile

Use `node:10-slim` instead of `node:10`.
This decreases the image size (`master`) from 1.22 GB -> 552 MB.

Use node:10-slim for Docker

---

src/components/inputs/IconInput.jsx

Fixes the following warning:
```
Warning: Failed prop type: Invalid prop `value` of type `string` supplied to `IconInput`, expected `array`.
in IconInput (created by SpecField)
in SpecField (created by SpecProperty)
in div (created by InputBlock)
in div (created by InputBlock)
in InputBlock (created by SpecProperty)
in SpecProperty (created by FunctionSpecProperty)
in div (created by FunctionSpecProperty)
in FunctionSpecProperty (created by PropertyGroup)
in div (created by PropertyGroup)
in PropertyGroup (created by LayerEditor)
in div (created by LayerEditorGroup)
in div (created by Motion)
in div (created by Motion)
in Motion (created by Collapse)
in Collapse (created by UnmountClosed)
in UnmountClosed (created by CollapseAlt)
in CollapseAlt (created by LayerEditorGroup)
in div …
```

IconInput value type should be string, not array

---

appveyor.yml

`lint-styles` was removed from Appveyor in https://github.com/maputnik/editor/pull/280/commits/1805aee7ba559327b6aa068d7662120f62d65c62 but it seems to work now.

Appveyor add again lint-styles

---

README.md

Use absolute URLs to make them appear on https://hub.docker.com/r/maputnik/editor/

Readme: Use absolute URLs for logo and sponsor images

---

src/components/App.jsx
src/config/tilesets.json
src/libs/style.js

This change is because of the MapTiler Cloud infrastructure upgrade:
https://www.maptiler.com/blog/2019/04/maptiler-cloud-infrastructure-upgrade.html
This PR should be merged after the OMT styles are reflecting this change.

Change Maptiler URLs

---

package-lock.json
package.json

The current editor uses a beta version of mapbox gl js.
We should switch to a stable release so that the [documentation of Mapbox Styles](https://docs.mapbox.com/mapbox-gl-js/style-spec/#paint-line-line-pattern) fits the editor behavior.
For example in line-pattern in this beta data-driven styling is not allowed fully.
Everything else should continue to work as expected

Update mapbox dependencies to current version

---

src/styles/_scrollbar.scss

Since Firefox 64 the following CSS properties are available:
https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-width
https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color
**Before:**
**This PR:**

Firefox scrollbar styling

---

src/components/layers/JSONEditor.jsx

Attempt to fix #484 by using 
`componentDidUpdate` 
instead of 
`getDerivedStateFromProps` and `shouldComponentUpdate`.
Demo:
https://1281-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html

Fix JSON-editor

---

src/components/Toolbar.jsx
src/components/map/FeaturePropertyPopup.jsx
src/components/map/MapboxGlMap.jsx

This fixes three small bugs (inspect mode inconsistency when switching renderer, duplicate key in `FeaturePropertyPopup`, inspect mode didn't count beyond 2) and cleans up popup rendering by re-using the DOM node for rendering.

Various cleanups regarding popups and inspect mode

---

src/components/App.jsx
src/components/modals/DebugModal.js
src/components/modals/ShortcutsModal.jsx

A PR for #460
@pathmapper to not add clutter to the toolbar, how about a hidden modal. Just press `!` for the debug modal (`?` to see the shortcuts)
Then you'll get a modal pop up with some debug options.
I figured because we don't display that these options are enabled in the UI anywhere at the moment, a novice user could accidentally enable these options. For this reason they will reset on browser refresh (we can change that later down the road)
I've also removed the url param method of enabling these feature as a part of this PR
Does that meet your requirements?
Demo: <https://1280-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.34/0/0>
Fixes #460 (...if @pathmapper likes it 😄 )

Added semi-hidden debug modal

---

src/components/App.jsx

Sometimes when editing a inputs `ctrl+z` was causing an app undo event and a native browser undo event at the same time. This prevents the browser from handling the undo event.

Prevent native browser undo/redo when handled by app

---

src/components/inputs/NumberInput.jsx
src/components/inputs/StringInput.jsx

Somewhere along the way we (probably me) broke the ability to enter intermediate values into string/number inputs. The editor was constantly trying to replace the value you entered with a 'valid' value.
This resulted in not being able to enter values like `0.1` because `0.` getting automatically 'fixed' to be `0`. Which is obviously not what I wanted 😄 
This change adds an 'editing' state to the inputs, it'll keep updating the map with the latest changes from the inputs, but will prevent the `props` from updating the input until you no longer have focus. 
If anybody has some time to give it a test https://1236-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.34/0/0

Fix for string/number inputs when inputting invalid of intermediate values

---

package-lock.json
package.json
src/components/App.jsx
src/components/Toolbar.jsx
src/components/map/FeatureLayerPopup.jsx
src/components/map/OpenLayersMap.jsx
src/components/modals/DebugModal.js
src/components/modals/SettingsModal.jsx
src/styles/_map.scss
src/styles/_popup.scss

Over the weekend I was trying to get an antarctic map rendering with `ol-mapbox-style` and some vector tiles that I've projected using `ogr2ogr`. I have a very hacked together version of that 'kinda works' (more on that in later PR's), however along the way I made a couple of improvements to the OL renderer.  
I've added
- Disable inspect mode for openlayers render as it doesn't work
- Added debug toolbox to tell me the current state of the openlayers map (mainly for debugging projections, but generally useful), note this is behind a setting in the debug modal
- Zoom display UI, the same as the mapbox-gl renderer
- Fixed rendering of rotate UI
Screenshot
Fixes #254

Further OpenLayers improvements

---

src/components/modals/AddModal.jsx

Fixes #471
There might be better ways to replace `UNSAFE_componentWillUpdate` as it seems a bit strange to use `shouldComponentUpdate()` when it's never expected to return `false`. But it's invoked also before rendering and the existing logic with `nextState` could be used.
Open for better solutions :smile:

Remove UNSAFE_componentWillUpdate

---

src/components/App.jsx
src/libs/apistore.js

This works in conjunction with https://github.com/maputnik/desktop/pull/5 to add support for running the desktop app on a port other than 8000, because many people already have something else running on 8000.

Add support for connecting to a local server on port other than 8000

---

src/config/tokens.json

https://www.maptiler.com/cloud/ have kindly given us a new key for the use in the editor.
It replaces the old key which was limited to 100k requests/month and caused https://github.com/maputnik/editor/issues/541 because this limit was exceeded.
Thanks @klokan !

Update Maptiler key

---

README.md

Besides https://github.com/maputnik/editor/issues/541, some things are not working anymore with `v1.5.0`, e.g. the _Klokantech Basic_ and _OSM Bright_ styles. So this PR adds the `v1.6.0-beta` to the readme.

Add 1.6.0-beta to readme

---

config/webpack.production.config.js
package.json
src/components/fields/ColorField.jsx
src/components/layers/LayerList.jsx

So to follow on from @pathmapper comment in https://github.com/maputnik/editor/pull/521#issuecomment-493949882 it does indeed look like the performance has suffered between `v1.5.0` and `v1.6.0`. Although the 84ms mentioned in https://github.com/maputnik/editor/issues/372 was clearly just incorrect results, see results from v1.5.0 below (no idea what mistake I made perviously)
The condition I'm testing is changing the background color of osm-liberty. The reults from the devtools performance profiler are as follows
v1.5.0
v1.6.0
If I run it in development it's significantly slower, I'm assuming all the react profiling metrics is causing some of that slow down. But for the following demonstration, lower numbers are better and don't compare them to the production builds above.
So the current …

LayerList performance improvements

---

src/styles/_map.scss

The color is currently white on a white div:

Set a color for the OpenLayers attribution control

---

src/components/layers/LayerEditor.jsx

`LayerSourceLayerBlock` was always included
fixes #568

Fix the layer type test in LayerEditor component

---

.circleci/config.yml
config/webpack.profiling.config.js
package.json

From https://github.com/maputnik/editor/pull/557#issuecomment-542103025
> Yeah that's right, so what I'm thinking is that we'll create 2 artifacts from the CI builds one will be the normal build we use to show in demos currently. The other for performance testing we'll include the react [profiling-in-production](https://gist.github.com/bvaughn/25e6233aeb1b4f0cdb8d8366e54a3977#profiling-in-production)
This PR adds a new build with profiling enabled to the artifacts directory `/profiling` so we can use the react profiler
Demo https://1558-84182601-gh.circle-artifacts.com/0/artifacts/profiling/index.html

Added profiling build to CI

---

src/components/layers/JSONEditor.jsx
src/components/modals/SourcesModal.jsx
src/components/sources/SourceTypeEditor.jsx
src/styles/_codemirror.scss
src/styles/_modal.scss
src/styles/index.scss

Added support for raw GeoJSON to the editor along with sizing edit to make the 'input block labels' take up only 30% of the space in the DataSources modal. 
Screenshot
Demo: https://1604-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html
Fixes #559

Add support for raw GeoJSON as source

---

src/components/map/MapboxGlMap.jsx

mapbox-gl will do the diff for us anyway, this was making large inline GeoJSON sources slow to update (ref #559)

Remove shouldComponentUpdate from <MapboxGlMap/>

---

.github/FUNDING.yml

Displays the "❤️ Sponsor" in the repository, more info:
https://help.github.com/en/github/building-a-strong-community/displaying-a-sponsor-button-in-your-repository
The link is the same as the one in the README

Activate sponsor button in GitHub

---

src/styles/_zoomproperty.scss

The delete icon is aligned with the bottom but it should be with the middle.
Use the same css as the `maputnik-make-data-function` and `maputnik-make-zoom-function` buttons.
Before:
After:

Simplify and fix vertical alignment of the delete button

---

src/components/fields/FunctionSpecField.jsx
src/components/fields/SpecField.jsx

Recent fixes to allowing you to reset the values of fields, caused issues with function fields. This was because previously those fields set the `value` of a property to it's `default`. Now we just pass the default value to the fields rather than mutating the value (see https://github.com/maputnik/editor/pull/563/files#diff-b98b1ae2788532d29e7217366330abaaL68). This resulted in the values being `undefined` when transitioning to 'function fields', causing the spec validator to throw an error.
This PR adds a new method `findDefaultFromSpec` which uses the default from the spec, else it falls back to a set of generic defaults (some properties don't have defaults).
I've also fixed `enum` to use the `<EnumInput />` again, which was previously defined in `<SelectInput/>`

Function field fixes

---

src/config/styles.json

Make osm-liberty the default style when you open the editor, because
- It's the one owned by the maputnik organisation
- It's a lovely style

Make osm-liberty the default style

---

src/components/inputs/StringInput.jsx
src/components/inputs/UrlInput.jsx
src/components/map/MapboxGlMap.jsx
src/components/modals/OpenModal.jsx
src/components/modals/SettingsModal.jsx
src/components/modals/SourcesModal.jsx
src/components/sources/SourceTypeEditor.jsx
src/components/util/SmallError.jsx
src/components/util/SmallError.scss
src/styles/_modal.scss
src/styles/_vars.scss
src/styles/index.scss

If the editor is loaded from `https://` (like on `https://maputnik.github.io/editor/`) show an error for url fields where the user is trying to use `http://` urls 
Demo: <https://1815-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
Fixes #374

Add open modal and source http/https errors

---

.circleci/config.yml
appveyor.yml

Node v8 is EOL: https://github.com/nodejs/Release#end-of-life-releases

Remove node v8 from test runners 

---

src/components/map/MapboxGlMap.jsx

Closes https://github.com/maputnik/editor/issues/593
Overwrites the default `maxZoom` of 22:
https://docs.mapbox.com/mapbox-gl-js/api/#map
**Demo:**
https://2055-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html

Increase maximum zoom level of the map to 24

---

src/codemirror-maputnik.css
src/components/layers/JSONEditor.jsx

When the JSON editor was added in https://github.com/maputnik/editor/commit/3cc9f450850deda37bdb193052a742b5ca105376, there was already styling for the codemirror `matchbrackets` addon defined but the addon itself was never added.
This PR adds this addon and removes the `text-decoration: underline` from CSS (it looked a bit weird because the underline was not fully visible).
~~Demo: https://2039-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html~~

Add matchbrackets addon to JSON editor

---

src/components/App.jsx
src/components/map/MapboxGlMap.jsx
src/components/map/OpenLayersMap.jsx
src/components/modals/DebugModal.js

This adds a link to OSM `https://www.openstreetmap.org/#map={ZOOM}/{LAT}/{LNG}` from the debug panel
To open the debug panel focus the editor then press `ESC` follow by `!`
Demo: <https://1981-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.36/0/0>

Link to OSM from debug panel

---

src/components/modals/SourcesModal.jsx
src/components/sources/SourceTypeEditor.jsx
src/styles/_components.scss

This PR adds the ability to add image/video sources
Demo: https://1971-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html
Adding images/video from
- https://docs.mapbox.com/mapbox-gl-js/example/image-on-a-map/
- https://docs.mapbox.com/mapbox-gl-js/example/video-on-a-map/
Notes:
- Coordinate fields could definitely to with UI/UX improvements as they take up a lot of vertical space at the moment. I think a later addition 
- The sources tab doesn't currently display the 'type' of the source once added. This is an existing issue and will be fixed separately
- When adding a new source the inputs don't get cleared. This is an existing issue and will be fixed separately

Added ability to add image/video sources

---

src/components/fields/ColorField.jsx

This was causing warning in the browser console.

'name' is not a required property of <ColorField />

---

src/styles/_components.scss

HTML pages start with a white background in most browsers, most articles which contain maps are also going to be on a white background. So if a style doesn't set a background layer at the moment the user will probably get a different outcome than they expect when they export the style.
Before, with 'Empty Style'
After, with 'Empty Style'

Make background map container white to match html page default

---

src/styles/_components.scss
src/styles/_layout.scss
src/styles/_vars.scss

The error bar beneath the map was overflowing into the layer editor.
Before
After

Fixed overflowing error bar

---

src/styles/_scrollbar.scss

I've moved from using a trackpad (no scrollbars) to a mouse (has scrollbars), and clicking/grabbing the scrollbar was a little awkward because it was so small (5px). This PR makes the scrollbar wider so it's easier to grab with the mouse pointer.
Note this only effects webkit browsers.

Wider scrollbar

---

src/components/AppLayout.jsx
src/components/layers/LayerList.jsx
src/styles/_layer.scss

Fix for 'jumping' `<LayerList/>` introduced in #630.
The issue was that we'd always call `element.scrollIntoView()` in certain circumstances if the selected item was already in scrollable view the layer would change scroll position.

Only scroll to selected item in <LayerList/> if not already in view.

---

src/components/modals/SourcesModal.jsx
src/config/tilesets.json

Thunderforest tiles are no longer 'heavy' as of v2 🎉(see https://github.com/maputnik/editor/issues/641#issuecomment-612593093)
Removed all references from 'heavy' from the UI.

Remove notes from thunderforest sources

---

src/components/inputs/FontInput.jsx

Fixes default values for `<FontInput/>`, it was previously was only picking up the first value of the array of values.
Demo <https://2502-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
Fixes #649

Fixed default values for <FontInput/>

---

src/components/App.jsx
src/components/layers/LayerEditor.jsx
src/components/layers/LayerSourceBlock.jsx

Adds missing inline error for 'source' field.
Demo <https://2508-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
Fixes #653

Added missing inline error for 'source' field

---

src/components/fields/FunctionSpecField.jsx
src/components/fields/_DataProperty.jsx
src/components/fields/_ZoomProperty.jsx
src/components/filter/FilterEditor.jsx
src/components/util/spec-helper.js

I've added _identity function_ support, screenshot below
You can also undo from a `["get", "property_name"]` expression back to a _identity function_.
Demo <https://2490-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
Fixes #640

Add support for identity functions

---

src/components/sources/SourceTypeEditor.jsx
src/components/util/codemirror-mgl.js

The `<SourceTypeEditor/>` was using the `mapbox-gl-style-spec` bring back `jsonlint`.
Demo <https://2539-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
Fixes #660

Added JSON linting back into <SourceTypeEditor/>

---

src/components/inputs/DynamicArrayInput.jsx
src/components/sources/SourceTypeEditor.jsx

Add `<DynamicArrayInput/>` to source tile urls to support multiple values
Demo <https://2549-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
Before
After
Fixes #656

Support multiple tiles URLs for source

---

src/components/Toolbar.jsx
src/styles/_input.scss
src/styles/_layer.scss
src/styles/_scrollbar.scss
src/styles/_toolbar.scss
src/styles/_vars.scss

I've made the layer list header always visible and also improved scrollbar styling/positioning for toolbar.
Demo <https://2547-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
Before - note that I've made the window small so the top toolbar overflows also
After
Fixes #646

Fix to make layer list header visible at all times

---

package-lock.json
package.json

Fixes https://github.com/maputnik/editor/issues/648 
From the [GL JS v1.10.0 release notes](https://github.com/mapbox/mapbox-gl-js/releases/tag/v1.10.0): 
> Avoid throwing errors when calling certain popup methods before the popup element is created
Demo: https://2446-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html

Update MB deps

---

src/components/Button.jsx
src/components/Toolbar.jsx
src/components/fields/_DeleteStopButton.jsx
src/components/fields/_ExpressionProperty.jsx
src/components/fields/_FunctionButtons.jsx
src/components/filter/FilterEditor.jsx
src/components/filter/FilterEditorBlock.jsx
src/components/inputs/DynamicArrayInput.jsx
src/components/inputs/EnumInput.jsx
src/components/inputs/MultiButtonInput.jsx
src/components/layers/LayerEditor.jsx
src/components/layers/LayerList.jsx
src/components/layers/LayerListGroup.jsx
src/components/layers/LayerListItem.jsx
src/components/map/MapboxGlMap.jsx
src/components/map/OpenLayersMap.jsx
src/components/modals/ExportModal.jsx
src/components/modals/Modal.jsx
src/components/modals/OpenModal.jsx
src/components/modals/SettingsModal.jsx
src/components/modals/ShortcutsModal.jsx
src/styles/_filtereditor.scss
src/styles/_layer.scss
src/styles/_modal.scss
src/styles/_toolbar.scss

This pull request improves the editor for the following users
- keyboard only users
- those with visual impairments, who use a screen reader for some, although not all of their editing
Although many of them are generally useful to people outside those groups also.
Added aria landmarks to describe the main areas of the editor. With MacOS 'voice over' enabled pressing `CTRL + ALT + U` you'll see
Added missing title attributes to all icon only buttons. Both mouse users when hovering the button and screen readers will get descriptive text.
Inaccessible `<Multibutton/>` component has been changed internally to be a group of radio buttons, whereas before it was `<button>`s. This improves screen reader accessibility, because it is now announced as a group. Also keyboard users can access it using …

Fix some accessibility issues

---

src/components/layers/JSONEditor.jsx
src/styles/_codemirror.scss

The JSON editor now displays a helper message for a couple of seconds if you keyboard tab to it.
> Press `ESC` to lose focus
This is _only_ present when focusing via keyboard (tab) and not mouse 
Related to #322

Added tip to JSON editor about how to unfocus

---

README.md

Fixes
- Updated logo to point to maputnik/design
- Removed broken dependency badges
- Stop aligning logo right because it looked bad on mobile
_Before_
_After_

Fixed README styling

---

.github/workflows/ci.yml

Closes #668
This works in in conjunction with https://github.com/maputnik/desktop/pull/14 and is using the existing build for the editor artifact.
Desktop binaries are available for download from the ci artifacts:

Integrate desktop builds in ci workflow

---

src/config/styles.json

The repos were renamed
https://github.com/openmaptiles/maptiler-basic-gl-style
https://github.com/openmaptiles/maptiler-toner-gl-style
and for _Toner_ there were also changes to the license and style.

Update Basic and Toner styles

---

src/components/MapMapboxGl.jsx

Fixes the regression reported in #674 by reverting https://github.com/maputnik/editor/commit/f3b8c5362ad40c4fe4c2517f47c7879d8d8a6093
Without `shouldComponentUpdate` the style provided in https://github.com/maputnik/editor/issues/674#issuecomment-623491287 isn't working. 
`shouldComponentUpdate` was removed for performance reasons (https://github.com/maputnik/editor/pull/571). We could look into the performance issue later, but for know I think it's better to fix this regression for the upcoming `v1.8.0` release.

Add again shouldComponentUpdate

---

src/components/App.jsx
src/components/FieldId.jsx

Once we select a layer the components key remains until we select another layer, regardless of whether we edit the layer id in the editor. This fixes the `<LayerEditor/>` component recycling on layer `id` edit, which has the consequences described in #718 
Fixes #718

Fix to not change layer key while editing layer

---

src/components/FilterEditor.jsx

Initial attempt at fixing #712, needs some testing. Feel free to give it a test with the generated demo link below and report any errors.
Fixes #712

Correctly upgrade old-style filter functions to expressions

---

.github/ISSUE_TEMPLATE/other-issue.md

I've created a `maputnik` tag on https://gis.stackexchange.com/questions/tagged/maputnik, so we now request in the issue template comment using this tag for SE questions.

Request using 'maputnik' tag for SE questions

---

.github/workflows/ci.yml
config/wdio.conf.js

Due to some issues with gecko 31, the version was fixed to gecko 30. Gecko is at 33 now, so we can again be on latest.

Use latest firefox

---

cypress/e2e/accessibility.cy.ts
cypress/e2e/driver.ts
cypress/e2e/history.cy.ts
cypress/e2e/keyboard.cy.ts
cypress/e2e/layers.cy.ts
cypress/e2e/map.cy.ts
cypress/e2e/modals.cy.ts
cypress/support/e2e.ts
package-lock.json
package.json
src/components/App.jsx
src/components/AppToolbar.jsx
src/components/LayerEditor.jsx
src/components/LayerList.jsx
src/components/MapMaplibreGl.jsx
src/libs/zoomcontrol.js

Added shellygo package.
Refactor driver and e2e tests.
Added data-wd attributes to missing places.

Refactor driver for E2E

---

cypress/e2e/modals.cy.ts
package-lock.json
package.json
src/components/App.tsx
src/components/FieldId.tsx
src/components/FieldMaxZoom.tsx
src/components/FieldMinZoom.tsx
src/components/FieldSource.tsx
src/components/FieldType.tsx
src/components/FilterEditor.tsx
src/components/MapMaplibreGl.tsx
src/components/ModalSettings.tsx
src/components/ModalSources.tsx
src/components/_DataProperty.tsx
src/components/_ZoomProperty.tsx
src/config/tokens.json
src/libs/codemirror-mgl.ts
src/libs/filterops.ts
src/libs/maplibre-rtl.ts
stories/FieldFunction.stories.jsx

This PR aims at updating MapLibre dependencies.
The main goal of this update is to allow adding terrain specification to the editor.
This requires version 4 of maplibre so currently it will use the pre-release.

Update MapLibre dependencies, add terrain editing

---

src/components/AppToolbar.tsx

Fixes #861
This should hopefully address the last item in the below issue of the missing logo.
I tested it locally and it seems to be working as expected, I hope this will be the case once deployed.
- #861

Fix missing logo

---

cypress/e2e/map.cy.ts
cypress/e2e/maputnik-driver.ts
package-lock.json
package.json
src/components/MapMaplibreGl.tsx

This replaces PR:
- #785
Before:
After:
This is based on the geocoder example in maplibre docs:
https://maplibre.org/maplibre-gl-js/docs/examples/geocoder/

Add nominatim search to maputnik

---

cypress/e2e/layers.cy.ts
src/components/InputNumber.tsx
src/components/InputSpec.tsx

Fixes #870
- #870
This regression bug was introduced as part of the refactoring of typescript.
Here:
- #848
I've added tests to cover the scenario so that it won't happen again, hopefully.

Removes number conversion for dirty input

---

README.md

Activating maputnik with `docker run` requires to bind port 80 from container and not 8888, because nginx is running with default config and listening port 80
For `npm run` port 8888 is explicitly set up [in config](https://github.com/maplibre/maputnik/blob/bc5ecfade6801e16df339a8caba766d28b88de56/vite.config.ts#L8).

Readme.md container port changed to 80

---

src/components/MapMaplibreGlFeaturePropertyPopup.tsx
src/styles/_popup.scss

Fixes #868
- #868
It solves all the block within blocks and all kind of controls that are not required which creates gaps.
I use a simple table, so the width is dynamic but it is always aligned for all the properties and the features.
Vary basic stuff.
There's still the layer popup, which I'm not sure I know what it is and might need to be fixed as well.
CC: @zstadler

Improve inspect hover UI

---

package-lock.json
package.json
src/components/MapMaplibreGl.tsx

close #892 
this changes works well for CJK fonts.

localIdeographFontFamily: false to load CJK fonts

---

.github/workflows/ci-desktop.yml

The `working-directory` option does not apply to the artifacts steps, so we have to specify the full paths

Fix desktop ci artifacts path

---

package-lock.json
package.json

This upgrade should fix the error of Firefox tests failing. See this issue for more details:
https://github.com/cypress-io/cypress/issues/29190

Upgrade Cypress to fix CI errors

---

package.json
src/config/styles.json

These are great looking permissively licensed styles maintained by a passionate open source communities. I think they should be included in the example styles. 🙂 
The thumbnails were uploaded to GitHub and should be available pretty much forever, I chose to triple the pixel density because the other thumbnails look bad on my high res monitor.

Add Versatiles Colorful as example style

---

src/components/MapMaplibreGlFeaturePropertyPopup.tsx

Current label, "Feature ID", creates a little bit of confusion. It's not clear that this label isn't really part of the feature properties.
For example, when we want to filter by feature id, we need to use `$id`
```
[==, "$id," 123] 
```

Update feature id label to $id in feature properties popup

---

README.md
src/config/styles.json

* Adds the Stadia Outdoors style (anticipating the question: the MapLibre domain and localhost development are whitelisted)
* Minor fixes to README as the npm commands seem to have changed slightly
* Reorder the empty style to the beginning; seems the logical place for it to me, but open for discussion

Add Stadia Outdoors style

---

src/config/styles.json

We have been added to the CORS (Cross-Origin Resource Sharing) allowlist, so we can use Americana on `maplibre.org`.
https://tile.ourmap.us/usage.html
This style is FOSS so it will be an especially great addition to the Maputnik default styles.

Add Americana and Protomaps Light styles

---

src/components/ModalSources.tsx

* When adding a new Raster or Raster-dem tile source, use `.png` as the hint for the tile URL hint prompt.
* Currently, the user is prompted for a Vector tile source (e.g., `.pbf`)
* If a new Mapnik user already has their XYZ raster Tile URL, then they may already know how to modify this text field.
* This change may be useful for new users and is intended for them.
* `.png` is a start.  It could be `.webp` or `.jpg`, or `.jpg`, or in the case of Esri there is no extension for the images.
* See [RobLabs.com/xyz](https://RobLabs.com/xyz) for sample XYZ raster tile URLs
---
* Steps to reproduce
* See [RobLabs.com/maputnik](https://roblabs.com/maputnik) for a working version of this fix for Maputnik
* On top menu bar:  *Data Sources* > In the *Add New Source* section > Change *Source Type* …

[user interface]: Use `.png` as the XYZ Tile URL format hint for raster & raster-dem tiles

---

CHANGELOG.md
src/components/ModalExport.tsx
src/components/ModalOpen.tsx

`showOpenFilePicker` and `showSaveFilePicker` are undefined on Firefox. With this pr, Maputnik uses the old behavior as a fallback. It keeps the naming "open" and "save" instead of "upload" and "download" to underline that the style stays within the browser and no actual upload happens.
@zstadler Could you give it a try, please?
- fixes https://github.com/maplibre/maputnik/issues/966
The "Save as" button gets hidden if `showSaveFilePicker` is not available since it would have no use.
<table>
<tr>
<td>
Chrome
</td>
<td>
Firefox
</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>

add fallback behavior for `showOpenFilePicker` and `showSaveFilePicker`

---

src/components/SmallError.scss
src/styles/_base.scss
src/styles/_codemirror.scss
src/styles/_components.scss
src/styles/_filtereditor.scss
src/styles/_input.scss
src/styles/_layer.scss
src/styles/_layout.scss
src/styles/_map.scss
src/styles/_modal.scss
src/styles/_popup.scss
src/styles/_toolbar.scss
src/styles/_zoomproperty.scss
src/styles/index.scss

SCSS is changing, giving a lot of runtime console warnings.
https://sass-lang.com/documentation/breaking-changes/import/
So we have to use `@use` instead of `@import` and a few other things. It's aligning more with css
Their migration tool did almost everything, and console warnings described remaining Changes
- https://sass-lang.com/documentation/breaking-changes/import/#automatic-migration

Use new scss syntax

---

.github/workflows/ci.yml
cypress/e2e/modals.cy.ts
src/components/App.tsx

Going from e.g. MapTiler to OpenLayers and back will lose the maptlier key.
This code finds the urls in the style that has "{key}" and insert the correct API keys
Fixes the error reported here, cc @nyurik 
- Fixes https://github.com/maplibre/maputnik/issues/874#issuecomment-2605896666
Related to:
- https://github.com/maplibre/maputnik/issues/869

Fix insertion of access tokens, when swapping renderer

---

src/config/styles.json

the stylejson url to versatiles colorful has changed from `https://tiles.versatiles.org/assets/styles/colorful.json` to `https://tiles.versatiles.org/assets/styles/colorful/style.json`

fix url to to versatiles colorful

---

CHANGELOG.md
src/components/FilterEditorBlock.tsx
src/components/InputMultiInput.tsx
src/styles/_filtereditor.scss

This PR fixes the silliness with the `maputnik-multibutton` requiring `maputnik-button` and `@extend` not working because not included in said file.
Fixes https://github.com/maplibre/maputnik/issues/1044
| Before | After |
|--------|--------|
| ![image](https://github.com/user-attachments/assets/0f4cd7a3-0359-4d0f-aaca-b346739cb760) | ![image](https://github.com/user-attachments/assets/8b8f4aa4-b672-4495-9454-864d756799cc) |
This also fixes the same issue a few lines up where `maputnik-delete-filter` refers to an not imprted `@extend`.

fix: Multi choice options style regression

---

src/config/styles.json

And add two styles from AWS Location Services... It's nice to have a hybrid satellite style I think.
Hosted the thumbnails on a S3 bucket on our MapLibre AWS account.

Remove broken Zoomstack styles

---

Dockerfile

This unblocks the CI
We already use node 22 in the CI most places, I just forgot the Dockerfile, and now that Node 18 is recently EOL it appear to be failing there.

Move docker to node 22

---

CHANGELOG.md
cypress/e2e/modals.cy.ts
src/components/App.tsx
src/components/AppToolbar.tsx
src/components/Doc.tsx
src/components/modals/Modal.tsx
src/components/modals/ModalAdd.tsx
src/components/modals/ModalDebug.tsx
src/components/modals/ModalExport.tsx
src/components/modals/ModalGlobalState.tsx
src/components/modals/ModalOpen.tsx
src/components/modals/ModalSettings.tsx
src/components/modals/ModalShortcuts.tsx
src/components/modals/ModalSources.tsx

This adds the ability to edit the global state.
I think it deserves a modal of its own since I don't think it should be part of other modals...
Here are some images:
Initial dialog with no variable:
After you click add a few times:
The state is updated as you change thing in the dialog.
I didn't complicated it to select the type of the variable, but this can be added later of if there's a requirement to do so, I meant to keep it simple for now.

Add global state modal

---

CHANGELOG.md
cypress/e2e/modals.cy.ts
src/components/modals/ModalSettings.tsx

Add a small drop down to select mercator or globe.
This isn't a fully covered field as one can set an expression there, but I believe this is good enough for most cases.
Before:
After:

Add globe support in Maputnik UI
