maplibre/maputnik

- Dockerfile
- README.md
- Added a Dockerfile to allow the editor to be served using docker containers
- Updated README with docker instructions
> Serve the editor using container

- src/config/layout.json
Purpose: Match structure and wording with Mapbox GL style spec.
> Reordered and renamed groups

- package.json
- src/components/Toolbar.jsx
- src/components/modals/ExportModal.jsx
> Export to Gist anonymously, related to maputnik/editor#3

- src/styles/_components.scss
- src/styles/_layout.scss
- src/styles/_toolbar.scss
- src/styles/index.scss
To facilitate embedding in other apps.
> Configurable toolbar top offset.

- src/components/fields/ColorField.jsx
- src/styles/_input.scss
I've added a color swatch to the color field in order to preview the color. See screenshots below
This should hopefully make editing slightly easier.
> Added color swatch to color field

- package.json
- src/codemirror-maputnik.css
- src/components/layers/JSONEditor.jsx
- src/vendor/codemirror/addon/lint/json-lint.js
I've added JSON linting to the JSON editor
This fixes issue #47
> Added JSON linting (#47)

- src/styles/_components.scss
Per https://github.com/maputnik/editor/issues/118
> Increase popup Z-index

- src/styles/_layout.scss
> Remove overflow hidden to allow modal to show in safari

- src/components/modals/OpenModal.jsx
- src/styles/_mixins.scss
- src/styles/_modal.scss
> Fix to add error notice when uploading invalid JSON

- config/webpack.config.js
- config/webpack.production.config.js
I forgot to change the build path since the move of webpack configs to `./config`, this fixes that.
> Fixed build path since move of webpack.config.* to ./config

- src/components/map/OpenLayers3Map.jsx
- src/styles/_map.scss
- src/styles/index.scss
Added support for gejson sources
Fix toVectorLayer map callback (`this` was undefined)
Improved ol css; show map controls
> Improved OpenLayers support

- src/template.html
Thanks for the amazing work on this project.  This pull request suggests a adding an animated loading indicator in place of the unstyled "Loading..." text.  I understand if you're not interested in adding such a thing.  In case you are, here is what it looks like (with a forced 3s load delay):
> Animated loading indicator

- circle.yml
- config/webpack.production.config.js
This allows for per branch / commit builds
For an example of such builds see https://4-84182601-gh.circle-artifacts.com/0/tmp/circle-artifacts.YhgElD3/build/index.html#12.24/47.3718/8.5481
This will allow us to review pull requests without having to checkout the branch locally. Which should hopefully speed up pull request reviews a little while also allowing no programmers to get involved in reviewing pull requests.
This fixes part of #123
> Per branch / commit builds

- README.md
This PR adds a related projects section to the README with a link and description for `maputnik-dev-server`
Closes #162
> Add related projects section

- src/components/modals/Modal.jsx
- src/styles/_modal.scss
Help wanted (label : ), help provided. 
Please let me know if there is anything wrong with this pull request. I’m new to open source.
> Modal scrolling #156

- src/components/Toolbar.jsx
- src/components/modals/ExportModal.jsx
See <https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/> for details
> Added rel="noopener noreferrer" to external links.

- src/components/map/MapboxGlMap.jsx
- src/libs/zoomcontrol.js
- src/mapboxgl.css
> Display zoom level #87

- src/components/App.jsx
Fix a regression, `fetchSources` was getting called on each change hammering the network and also locking up the UI (oooops!). This fixes that.
> Fix to stop fetchSources getting called on each change

- src/components/layers/LayerList.jsx
- src/styles/_layer.scss
> Add expand/collapse all layer groups feature (#130)

- package-lock.json
- package.json
- src/components/modals/ExportModal.jsx
This includes the commit from PR #214.
> Updated to mapbox-gl@0.43.0

- src/components/inputs/AutocompleteInput.jsx
- src/components/modals/AddModal.jsx
> Autocomplete fixes

- src/components/modals/AddModal.jsx
Temporary fix for issue described in comment https://github.com/maputnik/editor/issues/220#issuecomment-359111563
> Added guard to getSources

- src/styles/_modal.scss
> Fix for safari modal appearing below the overlay

- src/components/layers/LayerEditor.jsx
See comment in <https://github.com/maputnik/editor/issues/220#issuecomment-361296022>
> Added guard to <LayerSourceLayerBlock/> sourceLayerIds

- src/components/Toolbar.jsx
- src/styles/_modal.scss
- src/styles/_toolbar.scss
> Added version number to the UI

- src/components/App.jsx
- src/libs/style.js
This will mean that autocomplete is broken for sources without vector_layers key present
Related to #234
> Added guard in fetchSources

- src/components/App.jsx
- src/libs/style.js
> Do not expose fallback tokens during export

- package-lock.json
- package.json
- src/components/modals/ExportModal.jsx
> Updated mapbox-gl 0.43.0 -> 0.44.0

- src/components/icons/LayerIcon.jsx
- src/components/layers/LayerEditor.jsx
- src/components/layers/LayerTypeBlock.jsx
- src/components/modals/AddModal.jsx
- src/config/layout.json
Fixes #265 
Note: No support for `heatmap-color` yet. See <https://github.com/maputnik/editor/issues/265#issuecomment-366511333>
> Added heatmap layer support

- package-lock.json
- package.json
- src/components/map/MapboxGlMap.jsx
As discussed [here](https://github.com/lukasmartinelli/mapbox-gl-inspect/pull/12)
With that we have the same behavior as Mapbox studio.
> Block the popup on click in inspect mode

- src/components/layers/LayerEditorGroup.jsx
- src/styles/_react-collapse.scss
- src/styles/index.scss
> Fix to allow layer sections to expand smoothly

- package-lock.json
- package.json
- src/styles/_filtereditor.scss
- src/styles/_toolbar.scss
- src/styles/_zoomproperty.scss
Updated stylelint and related deps. Also fixed scss for new defaults in `stylelint-config-recommended-scss` with the exception of the `no-descending-specificity` rule (because that threw too many errors)
> Updated stylelint

- src/styles/_toolbar.scss
> Fix to allow beta version strings to not wrap

- .circleci/config.yml
I've contacted CircleCI and they enabled OSX builds for free. Thanks CircleCI!
> CircleCI OSX builds

- src/components/Button.jsx
- src/components/modals/OpenModal.jsx
- src/styles/_modal.scss
Also fixed button to reserve space in DOM (fixes #245)
> Added aria-label to public styles

- src/components/App.jsx
- src/components/AppLayout.jsx
- src/components/Toolbar.jsx
- src/components/modals/Modal.jsx
- src/components/modals/OpenModal.jsx
- src/components/modals/ShortcutsModal.jsx
- src/styles/_modal.scss
I've added keyboard shortcuts to the editor, you can see the shortcuts by pressing `?` when not focused on an input element. See screenshot below
I've also
- Move style update logic into one place
- Renames 'Source' -> 'Data Sources' to make it a little clearer and make the `d` shortcut easier to remember
> Keyboard shortcuts

- README.md
> Added link to <https://maputnik.github.io/donate>

- src/components/modals/LoadingModal.jsx
- src/components/modals/Modal.jsx
- src/components/modals/OpenModal.jsx
- src/styles/_components.scss
> Loading dialog

- src/components/modals/ExportModal.jsx
> Option to download styles with your own tokens

- src/components/App.jsx
- src/components/map/MapboxGlMap.jsx
> Undefined filter fix (color accessibility)

- src/components/App.jsx
- src/components/map/MapboxGlMap.jsx
Adding `?show-collision-boxes=true` to the URL enables this feature. This should also go into the UI in a future pull request
> Added 'show-collision-boxes' query parameter

- src/components/map/MapboxGlMap.jsx
- src/styles/_components.scss
> Added no WebGL error message to MapboxGL map component

- src/libs/style.js
> Fix glyph key replace

- src/components/layers/LayerListItem.jsx
> Switch visibility icons

- src/components/map/MapboxGlMap.jsx
> Added guard to map object

- src/config/styles.json
- src/config/tilesets.json
> Remove mapbox for the time being

- src/components/Button.jsx
- src/components/modals/OpenModal.jsx
- src/styles/_components.scss
Fixes #396
Take a look @pathmapper
> Show error if style fails to load and disabled button if input is empty

- src/components/Toolbar.jsx
- src/styles/_toolbar.scss
Closes: https://github.com/maputnik/editor/issues/251
> Get name from package.json

- src/components/fields/FunctionSpecField.jsx
- src/components/fields/_DataProperty.jsx
- src/components/fields/_FunctionButtons.jsx
This PR fixes issue #380 - data-driven styling was broken by updating the mapbox-style-spec.
> Fix for Issue #380

- src/config/styles.json
Resolves https://github.com/maputnik/editor/issues/412
> rawgit.com -> jsDelivr

- src/config/empty-style.json
- Replace glyphs URL with a functional one
- Remove non-functional sprite URL
- Remove metadata
> Update Empty Style

- src/components/modals/Modal.jsx
Test build <https://1095-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
Fixes #416
> Delay modal close until blur events have triggered

- src/config/layout.json
Closes https://github.com/maputnik/editor/issues/423
> Move image property

- package-lock.json
- package.json
- src/components/modals/ExportModal.jsx
Resolves https://github.com/maputnik/editor/issues/429
> Use style name for export filename if available

- package-lock.json
- package.json
- src/config/layout.json
Added support for
- [fill-extrusion-vertical-gradient](https://www.mapbox.com/mapbox-gl-js/style-spec/#paint-fill-extrusion-fill-extrusion-vertical-gradient)
- [symbol-z-order](https://www.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-symbol-z-order)
Also updated @mapbox/mapbox-gl-style-spec to v13.3.0
Demo link: <https://1105-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
> Style spec additions

- src/styles/_toolbar.scss
See <https://github.com/maputnik/editor/pull/392#issuecomment-427595172>. We should fix this properly at some point
CC @pathmapper
> Added hacks to fix styling issue

- src/components/App.jsx
- src/libs/urlopen.js
- test/functional/history/index.js
- test/functional/index.js
- test/functional/layers/index.js
- test/functional/map/index.js
- test/functional/modals/index.js
- test/functional/screenshots/index.js
Ref.: https://github.com/maputnik/editor/issues/436#issuecomment-432552078
> Warning when style parameter is used

- src/styles/_toolbar.scss
Firefox ESR:
**Before:**
**This PR:**
> Improve select styling

- src/components/inputs/AutocompleteInput.jsx
Fixes: https://github.com/maputnik/editor/issues/452
> Add z-index to autocomplete

- src/components/App.jsx
- src/components/map/MapboxGlMap.jsx
As requested in https://github.com/maputnik/editor/issues/202#issuecomment-417866441.
Preview:
https://74-139128409-gh.circle-artifacts.com/0/artifacts/build/index.html?show-overdraw-inspector=true#1.35/0/0
> Add 'show-overdraw-inspector' query parameter

- src/components/layers/LayerListItem.jsx
- src/styles/_layer.scss
This PR makes the whole layer label draggable in the sortable list.
Demo: <https://1209-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
Fixes #426
> Make whole layer label draggable

- src/styles/_layer.scss
- src/styles/index.scss
Ref.: https://github.com/maputnik/editor/issues/318
Demo: https://842-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html
This PR / before (animated GIF):
> Increase color contrast

- src/styles/_base.scss
- src/styles/_modal.scss
So it doesn't cause a visual jump when it loads.
> Fix the size of the logo in the survey modal

- src/styles/_layer.scss
Fix wobbling of the layer list when hovering over layers.
Demo: https://854-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html
Before:
> Fix layer list wobbling 

- src/config/styles.json
This change is for using the latest version of the style.
> Update empty-style URL

- src/components/App.jsx
> Revert "Use replaceAccessTokens in onStyleChanged"

- src/components/App.jsx
- src/libs/style.js
Fixes #404 (alternative to #465)
Demo: https://994-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html
> Use access token for fetchSources

- Dockerfile
> Dockerfile fix warning

- README.md
CLI binaries are available again for the latest release: https://github.com/maputnik/editor/issues/360, https://github.com/maputnik/desktop/pull/3
> Adding information regarding CLI

- README.md
Addresses https://github.com/maputnik/editor/issues/478#issuecomment-463547546.
cc @jdeboer-geoplan
> How to start externally accessible dev server

- README.md
Reverts maputnik/editor#504
This isn't working.
> Revert "Readme: Use absolute URLs for logo and sponsor images"

- package-lock.json
- package.json
- src/components/Toolbar.jsx
It's only supported in chrome and firefox and we can't feature detect this unfortunately.
Fixes #472
> Toggle color accessibility based on user agent

- src/components/App.jsx
Follow-up on #419 to fix #417.
> Set default renderer if undefined

- .circleci/config.yml
- appveyor.yml
> Remove node v11 from test runners

- src/config/styles.json
Added [Toner style](https://github.com/openmaptiles/toner-gl-style) and moved empty style to end of list.
Demo: https://1667-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html
> Update available styles

- src/mapboxgl.css
Fix css for compass icon and increase color contrast for navigation controls.
Before:
After:
> Fix css and increase color contrast for navcontrols

- src/styles/_popup.scss
Fixes https://github.com/maputnik/editor/issues/547
Demo: https://1723-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html
> Make popups scrollable

- src/config/styles.json
Closes #552
Demo: https://1777-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html
> Update OMT styles

- src/config/styles.json
Ref: https://github.com/maputnik/maputnik.github.io/pull/23
> Update thumbnail source for OSM Liberty

- package-lock.json
- package.json
- src/components/layers/JSONEditor.jsx
- src/styles/_codemirror.scss
- src/styles/_react-codemirror.scss
- src/styles/index.scss
I've changed the `<JSONEditor/>` from [react-codemirror2](https://www.npmjs.com/package/react-codemirror2) to interacting with [codemirror](https://codemirror.net/) directly. Some initial metrics
With the same test case, as described in https://github.com/maputnik/editor/pull/557#issuecomment-541628824
> So I've changed my condition for the performance metrics I'm now changing the 'max zoom' of the 'state' layer osm-liberty. In a way that it would cause a re-render of the mapbox-gl map. So for example with the current map zoom at 1, I would change the 'max zoom' of the 'state' layer between 6 and 7
Before change
After change
Also if you just grab the color picker for the background layer and hold it while moving you mouse to continually change color you'll notice it's much smoother. …
> react-codemirror2 -> codemirror directly

- src/components/fields/PropertyGroup.jsx
- src/components/inputs/ArrayInput.jsx
- src/components/inputs/EnumInput.jsx
- src/components/inputs/NumberInput.jsx
- src/components/inputs/StringInput.jsx
- src/components/modals/SettingsModal.jsx
- src/styles/_input.scss
@fredj @pathmapper as a fix for #560 how about adding them to the style settings? 
Demo: https://1538-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html
> Added support for more root level properties

- src/config/styles.json
- src/config/tilesets.json
Update the OS Zoomstack endpoints to the second release
> set OS Zoomstack endpoints to v2

- package-lock.json
- package.json
Demo: https://1960-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html
> Update mbgl and style-spec

- src/components/fields/_DataProperty.jsx
Demo: https://1701-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html
Fixes #535
> Fix zoom ordering for data property fields

- src/components/map/MapboxGlMap.jsx
Demo: https://1887-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html
Fixes #403
> Update map style even if inspectModeEnabled=true

- src/components/map/MapboxGlMap.jsx
While we fix `mapbox-gl-inspect`. To be removed again once fixed.
Demo: https://1877-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.35/0/0
Ref #576
> A hack fix for blocked popup

- src/components/map/MapboxGlMap.jsx
Fixes #589 
Demo: <https://1891-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
> Fix feature selection in <FeatureLayerPopup />

- src/components/fields/SpecField.jsx
Fixes #588 
Demo: <https://1897-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
> Added new fieldSpec.type 'resolvedImage'

- src/components/map/FeaturePropertyPopup.jsx
Fixes #609
Demo <https://2043-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
> Fix for stuck/unchanging pop-up in Inspect view

- src/components/inputs/CheckboxInput.jsx
- src/components/modals/ExportModal.jsx
Fixes console error warning about missing value.
> Added default to <CheckboxInput/> value to fix warning in console.

- src/components/map/FeatureLayerPopup.jsx
Fixes issue reported in https://github.com/maputnik/editor/issues/629#issuecomment-608187208
Demo <https://2412-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
> Fix color in <FeatureLayerPopup/>

- src/components/inputs/NumberInput.jsx
Fixes #633
To test interact with any `<NumberInput/>` including those with ranges (minzoom/maxzoom)
Demo <https://2455-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
> Fixes for <NumberInput/>

- src/components/layers/LayerList.jsx
- src/components/map/MapboxGlMap.jsx
Scrolls `<LayerListItem/>` into view when selected. This PR also fixes general selection bugs from `<FeatureLayerPopup/>` created by #620  
Demo <https://2434-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
Fixes #630
> Scroll selected <LayerListItem/> into view

- package-lock.json
- package.json
- src/components/App.jsx
- src/components/fields/DocLabel.jsx
- src/components/filter/FilterEditor.jsx
- src/components/inputs/StringInput.jsx
- src/components/layers/LayerIdBlock.jsx
- src/components/layers/LayerList.jsx
This PR fixes a bunch of errors and warnings from the browser console.
Comment about fixes inline in code.
> Fix a bunch of errors/warnings from the console

- src/config/tilesets.json
> Upgrade Thunderforest tilesets from v1 to v2

- src/components/map/MapboxGlMap.jsx
Demo <https://2498-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
Fixes #647
> Fixed crash raised in issue #647

- src/components/map/FeaturePropertyPopup.jsx
Attempt to close https://github.com/maputnik/editor/issues/657.
Demo: https://2369-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html
> Add feature id to FeaturePropertyPopup

- src/components/modals/ExportModal.jsx
- src/libs/apistore.js
- src/libs/style.js
This is a fix for #591. However at the moment that part is untested as I don't personally have maputnik/desktop setup and working. If someone has maputnik/desktop setup and wants to test the build, feel free. Otherwise I'll get round to it next week, when my brain is a little fresher
> Added style formatting into the api store

- src/components/map/FeaturePropertyPopup.jsx
> Add source name to inspect popup

- src/components/modals/ExportModal.jsx
Mapbox and Maptiler access tokens were swapped.
Demo: https://2475-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html
> Fix token input

- src/components/Button.jsx
- src/components/inputs/UrlInput.jsx
- src/components/modals/OpenModal.jsx
Fixed URL entry in open modal to use form submission, I've also improved the errors if protocol isn't present.
Demo <https://2590-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html#0.36/0/0>
Fixes #681
> Fix open modal URL entry to use form submission

- src/components/App.jsx
- src/components/layers/LayerList.jsx
Demo <https://2611-84182601-gh.circle-artifacts.com/0/artifacts/build/index.html>
Fixes #533
> Fix for updating available sources cache when updating style

- .github/ISSUE_TEMPLATE/bug_report.md
> Add issue template for bug report

- .github/ISSUE_TEMPLATE/other-issue.md
We need another template for issues which are no bug reports.
ref #670
> Add other issue template

- .codesandbox/ci.json
As mentioned in https://github.com/maputnik/editor/issues/456#issuecomment-634173970
You can read all about it at https://codesandbox.io/ci 
Closes #456
> Added back in codesandbox CI config

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/other-issue.md
Related https://github.com/maputnik/editor/issues/325
> Point users to https://gis.stackexchange.com/ in issue template

- config/webpack.config.js
- package.json
- sandbox.config.json
See `https://github.com/codesandbox/codesandbox-client/issues/3392` for details. Added new `start-sandbox` script to `package.json`
> Disable host check for codesandbox

- src/components/InputDynamicArray.jsx
Fixes #707
See #707 for full description of issue.
> Remove key/value from style when editing style results in empty array

- src/components/FieldFunction.jsx
- src/components/_DataProperty.jsx
- src/components/_ZoomProperty.jsx
Added 'base' options to the UI for old style functions.
Fixes #710
> Added 'base' to functions

- package-lock.json
- package.json
- src/components/ModalExport.jsx
- src/styles/_modal.scss
Adds HTML export option to export model
Closes #705
> Added HTML export option to export modal.

- .github/workflows/ci.yml
https://docs.npmjs.com/cli/v8/commands/npm-ci
> Use npm ci for workflow

- src/components/ModalSources.jsx
- src/components/ModalSourcesTypeEditor.jsx
Added additional checkbox to set the cluster attribute when adding a GeoJson source
> Added checkbox for cluster attribute 

- index.html
This PR fixes the missing facicon.
As part of the migration to vite, this issue was introduced.
- #836
> Fix favicon

- .github/FUNDING.yml
- CODE_OF_CONDUCT.md
- FUNDING.yml
- LICENSE
- README.md
- SECURITY_POLICY.txt
I believe this solves most of the missing checkboxes:
- https://github.com/maplibre/maplibre/issues/352
Let me know if there's anything else missing.
Other configuration can be done after the repo has been migrated I believe.
> Prepare for on boarding

- package-lock.json
- package.json
- patches/mapbox-gl-inspect+1.3.1.patch
This is a temporary fix for:
- #871
The fix is using `patch-package` to fix the part of the code that is causing the issue, I believe.
Initial tests shows that this is fixing the issue, I hope it is not introducing other issues.
A proper fix and also using the maplibre package will be done once a repo is migrated as can be expected after the following PR is resolved:
- https://github.com/maplibre/maplibre/issues/359
> Temp fix using patch-package for maplibre-inspect issue

- package-lock.json
- package.json
- src/components/MapMaplibreGl.tsx
This is to update geocoder to latest version which now have types and is fully modernized.
> Update geocoder to 1.6.0

- src/config/styles.json
Add OSM OpenMapTiles to style gallery list
Fixes #949
Before
After
> Fixes #949 Add OSM OpenMapTiles to style gallery list

- CHANGELOG.md
- src/config/styles.json
Changes: https://github.com/protomaps/basemaps/blob/main/CHANGELOG.md#styles-v400--tiles-v400
> Update Protomaps Light gallery style to v4

- src/components/FilterEditorBlock.tsx
- src/styles/_filtereditor.scss
Include before/after visuals or gifs if this PR includes visual changes.
> fix: fix filter-editor style

- README.md
This is a quick typo fix for the Tests section of the readme file.
> Chore: Quick Typo fix in readme

- CHANGELOG.md
- package-lock.json
- package.json
- src/components/App.tsx
Remove react-autobind dependency
> Remove react autobind

- CHANGELOG.md
- cypress/e2e/modals.cy.ts
- src/components/App.tsx
- src/components/ModalExport.tsx
- src/components/ModalSettings.tsx
- src/config/styles.json
- src/config/tilesets.json
- src/config/tokens.json
- src/libs/field-spec-additional.ts
- src/libs/style.ts
- src/locales/de/translation.json
- src/locales/fr/translation.json
- src/locales/he/translation.json
- src/locales/it/translation.json
- src/locales/ja/translation.json
- src/locales/zh/translation.json
- Add LocationIQ access token field to settings and export modals
- Include LocationIQ Streets style in gallery
- Support automatic token replacement for LocationIQ URLs
- Add LocationIQ tileset configuration
- Include translations for all supported languages
> Add LocationIQ as supported map provider
